var express=require('express');var mongoose=require('mongoose');var cors=require('cors');var dotenv=require('dotenv');var userRoutes=require('./userRoutes');
dotenv.config();
var app=express();var PORT=process.env.PORT||5000;
app.use(cors());app.use(express.json());
var MONGO_URI=process.env.MONGO_URI||'mongodb://localhost:27017/crossword';
mongoose.connect(MONGO_URI).then(function(){console.log('MongoDB connected');return seedDemoPuzzle();}).catch(function(err){console.log('MongoDB failed: '+err.message);process.exit(1);});
var CellSchema=new mongoose.Schema({row:{type:Number,required:true},col:{type:Number,required:true},answer:{type:String,required:true},number:{type:Number,default:null}},{_id:false});
var WordSchema=new mongoose.Schema({id:{type:String,required:true},number:{type:Number,required:true},direction:{type:String,required:true},startRow:{type:Number,required:true},startCol:{type:Number,required:true},length:{type:Number,required:true},clue:{type:String,required:true}},{_id:false});
var PuzzleSchema=new mongoose.Schema({title:{type:String,default:'Puzzle'},difficulty:{type:String,default:'easy'},size:{rows:{type:Number,required:true},cols:{type:Number,required:true}},cells:{type:[CellSchema],required:true},words:{type:[WordSchema],required:true},active:{type:Boolean,default:true}},{timestamps:true});
var ScoreSchema=new mongoose.Schema({playerName:{type:String,default:'Anonymous'},score:{type:Number,required:true},time:{type:Number,required:true},hints:{type:Number,default:0}},{timestamps:true});
var Puzzle=mongoose.model('Puzzle',PuzzleSchema);var Score=mongoose.model('Score',ScoreSchema);
app.use('/api/auth',userRoutes);
app.get('/api/puzzle/random',function(req,res){Puzzle.countDocuments({active:true}).then(function(total){if(total===0)return res.status(404).json({success:false,message:'No puzzles'});var skip=Math.floor(Math.random()*total);return Puzzle.findOne({active:true}).skip(skip).lean();}).then(function(puzzle){if(puzzle)res.json({success:true,puzzle:puzzle});}).catch(function(err){res.status(500).json({success:false,message:err.message});});});
app.get('/api/puzzles',function(req,res){Puzzle.find().lean().then(function(p){res.json({success:true,puzzles:p});}).catch(function(err){res.status(500).json({success:false,message:err.message});});});
app.post('/api/puzzle',function(req,res){Puzzle.create(req.body).then(function(p){res.status(201).json({success:true,puzzle:p});}).catch(function(err){res.status(400).json({success:false,message:err.message});});});
app.post('/api/scores',function(req,res){var d=req.body;Score.create({playerName:d.playerName,score:d.score,time:d.time,hints:d.hints}).then(function(s){res.status(201).json({success:true,score:s});}).catch(function(err){res.status(400).json({success:false,message:err.message});});});
app.get('/api/scores/leaderboard',function(req,res){Score.find().sort({score:-1}).limit(10).lean().then(function(s){res.json({success:true,scores:s});}).catch(function(err){res.status(500).json({success:false,message:err.message});});});
app.get('/api/health',function(req,res){res.json({status:'ok'});});
function seedDemoPuzzle(){return Puzzle.deleteMany({}).then(function(){return Puzzle.create({title:'Easy Fun Puzzle',difficulty:'easy',size:{rows:9,cols:9},cells:[{row:0,col:0,answer:'C',number:1},{row:0,col:1,answer:'A'},{row:0,col:2,answer:'T'},{row:0,col:3,answer:'S'},{row:1,col:0,answer:'O'},{row:1,col:2,answer:'R',number:2},{row:1,col:3,answer:'U'},{row:1,col:4,answer:'N'},{row:2,col:0,answer:'L',number:3},{row:2,col:1,answer:'I'},{row:2,col:2,answer:'O'},{row:2,col:3,answer:'N'},{row:3,col:0,answer:'D'},{row:3,col:2,answer:'S',number:4},{row:3,col:3,answer:'U'},{row:3,col:4,answer:'N'},{row:4,col:0,answer:'S',number:5},{row:4,col:1,answer:'T'},{row:4,col:2,answer:'A'},{row:4,col:3,answer:'R'},{row:5,col:0,answer:'T'},{row:5,col:2,answer:'I',number:6},{row:5,col:3,answer:'C'},{row:5,col:4,answer:'E'},{row:6,col:0,answer:'A',number:7},{row:6,col:1,answer:'N'},{row:6,col:2,answer:'T'},{row:7,col:0,answer:'R'},{row:7,col:2,answer:'E',number:8},{row:7,col:3,answer:'Y'},{row:7,col:4,answer:'E'},{row:8,col:0,answer:'S',number:9},{row:8,col:1,answer:'E'},{row:8,col:2,answer:'A'},{row:8,col:3,answer:'T'}],words:[{id:'a1',number:1,direction:'across',startRow:0,startCol:0,length:4,clue:'Small pet that says meow'},{id:'a2',number:2,direction:'across',startRow:1,startCol:2,length:3,clue:'Move fast on your feet'},{id:'a3',number:3,direction:'across',startRow:2,startCol:0,length:4,clue:'Big cat with a mane'},{id:'a4',number:4,direction:'across',startRow:3,startCol:2,length:3,clue:'Bright star in the sky'},{id:'a5',number:5,direction:'across',startRow:4,startCol:0,length:4,clue:'Shining light in night sky'},{id:'a6',number:6,direction:'across',startRow:5,startCol:2,length:3,clue:'Frozen water'},{id:'a7',number:7,direction:'across',startRow:6,startCol:0,length:3,clue:'Small insect in colonies'},{id:'a8',number:8,direction:'across',startRow:7,startCol:2,length:3,clue:'Organ used to see'},{id:'a9',number:9,direction:'across',startRow:8,startCol:0,length:4,clue:'Place to sit at a table'},{id:'d1',number:1,direction:'down',startRow:0,startCol:0,length:9,clue:'Playing cards or calendar pages'},{id:'d3',number:3,direction:'down',startRow:2,startCol:2,length:5,clue:'Opposite of liquid or gas'}]});}).then(function(){console.log('Puzzle seeded!');}).catch(function(err){console.log('Seed error: '+err.message);});}
app.listen(PORT,function(){console.log('Server running at http://localhost:'+PORT);});


